#
# Name: Edgar Villagran
# Assignment 1
# ZID: z1861047
# Date: 1/24/2020

CC=g++
CCFLAGS =-ansi -Wall -std=c++11

Assign1: Assign1.o
	$(CC) $(CCFLAGS) -o Assign1 Assign1.o

Assign1.o: Assign1.cc
	$(CC) $(CCFLAGS) -c Assign1.cc

clean:
	-rm *.o Assign1
