# Name: Edgar Villagran
# Assignment 2
# ZID: z1861047
# Date: 2/07/2020

CC = g++
CCFLAGS = -Wall -std=c++11

Assign4: Assign4.o
	$(CC) $(CCFLAGS) -o Assign4  Assign4.o
Assign4.o: Assign4.cc
	$(CC) $(CCFLAGS) -c Assign4.cc
clean:
	-rm *.o Assign4

